# -*- coding: utf-8 -*-
"""Diffchecker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sb-cbGI6nDvLzUu5vwjfqUAdw1qL9jiH

# Reading elements from text file
"""

def read_elements(file):
  ans = []
  for i in file:
    sub_ans = i[:-1].split(' ')
    for j in sub_ans:
        ans.append(j)
  
  return ans

source = open("source.txt","r")
read_source = source.readlines()

elements_source = read_elements(read_source)
elements_source = [str.lower(i) for i in elements_source]
print(elements_source)

destination = open("destination.txt","r")
read_destination = destination.readlines()

elements_destination = read_elements(read_destination)
elements_destination = [str.lower(i) for i in elements_destination]
print(elements_destination)

# print(elements_source.count('cipro\uf002oxacin'))
# print(elements_source[340])
# print(len(elements_source[340]))

# print(elements_destination.index('cipro\uf002oxacin'))
# print(elements_destination[395])
# print(len(elements_destination[20]))

"""# Diff-Checker"""

def diffcheck(source , destination):
  s = [i for i in source]
  d = [i for i in destination]
  for i in d:
    if(s.count(i) > 0):
      s[s.index(i)] = " "
      d[d.index(i)] = " "
    # else:
    #   d[destination.index(i)] += " - not found"

  return s,d

print("Source : ",elements_source)
print("Destination : ",elements_destination)

s_ , d_ = diffcheck(elements_source , elements_destination)

print(s_)
print(d_)

c1 , c2 = 0 , 0
emp1 , emp2 = [] , []
for i in s_:
  if(i != " "):
    c1 += 1
    emp1.append(i)

for i in d_:
  if(i != " "):
    c2 += 1
    emp2.append(i)

print(c1)
print(c2)

print(emp1)
print(emp2)